#!/usr/bin/env bash

docker run -it --rm \
    -u $(id -u):$(id -g) \
    -v ~/.m2:/var/maven/.m2 \
    -e MAVEN_CONFIG=/var/maven/.m2 \
    -v "$(pwd)":/app \
    -w /app \
    maven:slim \
    mvn -Duser.home=/var/maven $@
